# Copyright 2022 Google LLC
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

# Contains bazel rules for ocpdiag_test_pkg and other OCPDiag helpers.

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

bzl_library(
    name = "ocpdiag_bzl",
    srcs = ["ocpdiag.bzl"],
)
