workspace(name = "ocpdiag")

# First load all the repositories we need.
load("//ocpdiag:build_deps.bzl", "load_deps")
load_deps()
# Some of these repositories have dependencies of their own,
# with getter methods. We need to call these from a separate
# bazel file, since there are bazel load statements that fail
# before the above initial load is complete.
load("//ocpdiag:secondary_build_deps.bzl", "load_secondary_deps")
load_secondary_deps()
# Finally, gRPC has dependencies that have dependencies of their
# own. We cannot include these in the load_extra_ocpdiag_deps file
# for the same reason we can't include the load_extra_ocpdiag_deps
# functionality in the original load_ocpdiag_deps function.
load("//ocpdiag:tertiary_build_deps.bzl", "load_tertiary_deps")
load_tertiary_deps()

# Configure toolchain based on system compiler
load("//toolchain/cpp:configure_cc_toolchain.bzl", "configure_cc_toolchain")
configure_cc_toolchain(name = "configure_gcc")

register_toolchains(
    "//toolchain/cpp:grte_toolchain",
    "//toolchain/python:py3_6_exec_toolchain",
    "//toolchain/python:py3_6_google_runtime_toolchain",
    "//toolchain/python:py3_8_toolchain",
)
